<?php
/**
 * Created by PhpStorm.
 * User: ghedger
 * Date: 7/12/17
 * Time: 7:44 PM
 */

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SignRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class SignRepository extends EntityRepository
{
}
