<?php
/**
 * Created by PhpStorm.
 * User: ghedger
 * Date: 7/12/17
 * Time: 3:58 PM
 */
// src/AppBundle/Entity/GameLogRepository.php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GameLogRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GameLogRepository extends EntityRepository
{
}
